### ISSUE TITLE
Whois only works on last joined channel

### ISSUE THREAD

**Issue by realJoshByrnes** [ozjd/IRC2017#2]
Steps to reproduce

JOIN %#The\bLobby
JOIN %#Test
WHOIS NICK

where NICK is in %#The\bLobby but not %#Test

Result: No such nick
Expected: WHOIS REPLY

**Comment by jyonxo** [comment]
I cant reproduce this. I had two connections in two different rooms and I could still find the user.

I have found a bug where if a user is not in a channel it will throw up, but apart from that it works fine. Are you by any chance getting confused because mIRC is automatically setting mode +i?

If the user is invisible it wont show up

[12:08] * >Sky sets mode: +i

-> TK2CHATCHATA01 WHOIS >sky
<- :TK2CHATCHATA01 401 sky >sky :No such nick

[12:13] * >Sky sets mode: -i

-> TK2CHATCHATA01 WHOIS >sky
<- :TK2CHATCHATA01 311 sky >Sky 00112233554477668899AABBCCDDEE14 GateKeeper * :
<- :TK2CHATCHATA01 319 sky >Sky :%#test
<- :TK2CHATCHATA01 312 sky >Sky TK2CHATCHATA01 :
<- :TK2CHATCHATA01 317 sky >Sky 2 1495854863 :seconds idle, signon time
<- :TK2CHATCHATA01 318 sky >Sky :End of /WHOIS list

-> TK2CHATCHATA01 WHOIS sky
<- :TK2CHATCHATA01 311 sky sky CF8E66B04B8798ED GateKeeperPassport * :
<- :TK2CHATCHATA01 319 sky sky :%#The\bLobby
<- :TK2CHATCHATA01 312 sky sky TK2CHATCHATA01 :
<- :TK2CHATCHATA01 317 sky sky 0 1495854863 :seconds idle, signon time
<- :TK2CHATCHATA01 318 sky sky :End of /WHOIS list

Two different rooms, worked fine. I will commit the bug fix for channel issue. Can you test again making sure the user doesnt have INVISIBLE mode on?
