### ISSUE TITLE
/restart command

### ISSUE THREAD

**Issue by realJoshByrnes** [ozjd/IRC2017#4]
Restart command would be great for Admins (not Sysops or Guides) to restart the server.

Would require bug #3 to be fixed first.

**Comment by jyonxo** [comment]
Bug #3 would not need to be fixed as if you trigger from inside the application I will have a chance to clean up the sockets gracefully first before ending the application.

We might want to think of the wider picture here rather than just having a /restart, a way to delve into the server for admins. Maybe a bigger feature would be better? Also rather than an Admin being able to restart the server, I would rather have it come from a better authenticated channel such as server to server. 

John was going to have his website manage the IRC Service. Let's consider this better first, unless theres some real need for this feature.

**Comment by jyonxo** [comment]
IRC7 will at some point transition over to AWS Elastic Beanstalk where we can restart it there, I still think restarting from inside is not a good idea. Gonna drop this one.
